# Generated by Django 5.2.2 on 2025-06-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitecheck',
            options={'ordering': ['-date'], 'verbose_name': 'Проверка статуса', 'verbose_name_plural': 'Проверки статусов'},
        ),
        migrations.AlterField(
            model_name='sitecheck',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
