# Generated by Django 5.2.2 on 2025-06-11 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitecheck_options_alter_sitecheck_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmonitoredsite',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='sitecheck',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='core.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='sitecheck',
            name='monitored_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='core.monitoredsite', verbose_name='Отслеживаемый сайт'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(verbose_name='ID платежа')),
                ('payload', models.CharField(verbose_name='Тип оплаты')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='core.client', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
                'ordering': ['-date'],
            },
        ),
    ]
